
from langchain.agents.factory import create_agent
from langchain_openai import ChatOpenAI
from pydantic import BaseModel, Field
import os
from dotenv import load_dotenv
from langchain_openai import ChatOpenAI
load_dotenv()
llm = ChatOpenAI(
    model="qwen2-vl-72b-instruct",
    openai_api_key=os.getenv("DASHSCOPE_API_KEY"),
    openai_api_base="https://dashscope.aliyuncs.com/compatible-mode/v1",
    use_responses_api=True
)

class ContactInfo(BaseModel):
    """Contact information for a person."""

    name: str = Field(description="The name of the person")
    email: str = Field(description="The email address of the person")
    phone: str = Field(description="The phone number of the person")
    poem: str = Field(description="The poem generated by the user") # I added this as well

agent = create_agent(model=llm, response_format=ContactInfo)

for token in agent.stream(
    {
        "messages": [
            {
                "role": "user",
                "content": "Please first write a poem and then convert it to binary and then extract contact info from name: John Doe, email: john@example.com, phone: (555) 1. For name, email and phone, use small letter in keys."
            }
        ]
    },
    stream_mode="messages",
):
    for block in token[0].content_blocks:
        if isinstance(block, dict) and block.get("type") == "text" and block.get("text"):
            print(block.get("text"), end="")
